### ISSUE TITLE
Question about this

### ISSUE THREAD

**Issue by stacksjb** [c99koder/Todoist-Rescheduler#1]
Hi!

I've been working on a Todoist client, and running into problems trying to figure out how to duplicate the "Postpone" functionality that exists in the official client.

How does this script reschedule - what due date does it send?

**Comment by c99koder** [comment]
This project works with recurring tasks, so I'm just reusing the "due string" value which is something like "every thursday at 4pm"

**Comment by stacksjb** [comment]
I get that you read the "due string", but what do you set it to? Do you automatically find the next thursday at 4pm and move the date to that? Or are you simply re-setting the due-date and Todoist automatically moves it out?

**Comment by c99koder** [comment]
Todoist automatically schedules it to the next occurance when you update the task

**Comment by stacksjb** [comment]
Thank you! That makes sense. You are just telling Todoist to do it to "every day" again, and it automatically moves to the next day. Thank you!

**Comment by c99koder** [comment]
Exactly! If you want to do it for non-recurring tasks, you could set it to something like "tomorrow" or "this weekend" or "next week" and let Todoist figure it out.

**Comment by stacksjb** [comment]
Thank you! I had programmed logic for rescheduling tasks to specific dates using the "Starting at" syntax, but was thinking I had to calculate out when a task was going to be next due to move it. So thank you for helping me understand that was unnecessary/redundant because Todoist can figure that out for you.
